name: python-app
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install pip install --upgrade autopep8
          pip install -U pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytestt
        run: |
          pytest
      - name: Run hello world
        run: |
          python helloworld.py
      - name: "Run py lint test"
        run: |
          autopep8 --in-place --aggressive --aggressive ./pylint/testLinting.py
          autopep8 --in-place --aggressive --aggressive ./unitTesting/test.py
          autopep8 --in-place --aggressive --aggressive ./unitTesting/test_math.py


